# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef55f5c3423d983ae7975ea01cc77a008050b8e8319f12d4c3c4e90e1174622f79642e1a7c62b423fc0bedd5ca06bd65eec26bd1a2ef41bad535e4b5030f5ece

test:
  secret_key_base: 62749111937d2e9668ee60fec732c4186d8d1ce5d4c72df2be3bc991fbbccb09ee78e6d17590d2003edc613f9d8804d5c601ed77faa17e46e4721c6a0507d8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
